# Dockerfile for the Python backend
FROM python:3.9-slim-buster

WORKDIR /app

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src /app/src

CMD ["python", "./src/main.py"]
